//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthToken
    {
        public int Id { get; set; }
        public string Token { get; set; }
        public System.DateTime Expiration { get; set; }
        public Nullable<int> ApiUser_Id { get; set; }
    
        public virtual ApiUser ApiUser { get; set; }
    }
}
