//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaryEntry
    {
        public int Id { get; set; }
        public double Quantity { get; set; }
        public Nullable<int> FoodItem_Id { get; set; }
        public Nullable<int> Measure_Id { get; set; }
        public Nullable<int> Diary_Id { get; set; }
    
        public virtual Diary Diary { get; set; }
        public virtual Food Food { get; set; }
        public virtual Measure Measure { get; set; }
    }
}
