//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Measure()
        {
            this.DiaryEntries = new HashSet<DiaryEntry>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public double Calories { get; set; }
        public double TotalFat { get; set; }
        public double SaturatedFat { get; set; }
        public double Protein { get; set; }
        public double Carbohydrates { get; set; }
        public double Fiber { get; set; }
        public double Sugar { get; set; }
        public double Sodium { get; set; }
        public double Iron { get; set; }
        public double Cholestrol { get; set; }
        public Nullable<int> Food_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiaryEntry> DiaryEntries { get; set; }
        public virtual Food Food { get; set; }
    }
}
